/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const afterUpdate: typeof import('svelte')['afterUpdate']
  const beforeUpdate: typeof import('svelte')['beforeUpdate']
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const getAllContexts: typeof import('svelte')['getAllContexts']
  const getContext: typeof import('svelte')['getContext']
  const getStores: typeof import('$app/stores')['getStores']
  const hasContext: typeof import('svelte')['hasContext']
  const navigating: typeof import('$app/stores')['navigating']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const page: typeof import('$app/stores')['page']
  const setContext: typeof import('svelte')['setContext']
  const tick: typeof import('svelte')['tick']
  const updated: typeof import('$app/stores')['updated']
}
